// Category mappings for filtering deadlines
export const CATEGORY_MAPPINGS: Record<string, string[]> = {
  tax: [
    // Federal Tax
    'BAS_QUARTERLY', 'BAS_MONTHLY', 'GST', 'INCOME_TAX', 
    'COMPANY_TAX', 'FBT', 'PAYG_INSTALMENTS', 'TPAR',
    // Excise & Special Taxes
    'FUEL_EXCISE', 'LUXURY_CAR_TAX', 'WINE_EQUALISATION_TAX', 
    'TOBACCO_EXCISE', 'ALCOHOL_EXCISE', 'PETROLEUM_RESOURCE_RENT_TAX', 
    'MAJOR_BANK_LEVY', 'FUEL_TAX_CREDITS',
    // NZ Tax
    'GST_MONTHLY', 'GST_TWO_MONTHLY', 'GST_SIX_MONTHLY', 
    'INCOME_TAX_RETURN', 'COMPANY_TAX_RETURN', 'FBT_QUARTERLY', 'FBT_ANNUAL',
    'PROVISIONAL_TAX_STANDARD', 'PROVISIONAL_TAX_RATIO', 'PROVISIONAL_TAX_AIM'
  ],
  payroll: [
    // AU Payroll
    'PAYG_WITHHOLDING', 'STP_FINALISATION',
    'PAYROLL_TAX_NSW', 'PAYROLL_TAX_NSW_ANNUAL',
    'PAYROLL_TAX_VIC', 'PAYROLL_TAX_VIC_ANNUAL',
    'PAYROLL_TAX_QLD', 'PAYROLL_TAX_QLD_ANNUAL',
    'PAYROLL_TAX_SA', 'PAYROLL_TAX_SA_ANNUAL',
    'PAYROLL_TAX_WA', 'PAYROLL_TAX_WA_ANNUAL',
    'PAYROLL_TAX_TAS', 'PAYROLL_TAX_TAS_ANNUAL',
    'PAYROLL_TAX_NT', 'PAYROLL_TAX_NT_ANNUAL',
    'PAYROLL_TAX_ACT', 'PAYROLL_TAX_ACT_ANNUAL',
    // NZ Payroll
    'PAYE', 'PAYE_LARGE_EMPLOYER', 'EMPLOYER_DEDUCTIONS'
  ],
  compliance: [
    // Corporate Compliance
    'ASIC_ANNUAL_REVIEW', 'DIVISION_7A_LOANS',
    // Workers Comp
    'WORKERS_COMP_NSW', 'WORKERS_COMP_VIC', 'WORKERS_COMP_QLD', 
    'WORKERS_COMP_SA', 'WORKERS_COMP_WA', 'WORKERS_COMP_TAS', 
    'WORKERS_COMP_NT', 'WORKERS_COMP_ACT',
    // Fair Work
    'WGEA_REPORTING', 'LONG_SERVICE_LEAVE', 'ANNUAL_LEAVE_LOADING',
    'MODERN_AWARD_UPDATE',
    // Other Compliance
    'R_AND_D_TAX_INCENTIVE', 'EMDG_APPLICATION'
  ],
  super: [
    'SUPER_GUARANTEE', 'SUPER_GUARANTEE_INCREASE',
    // NZ
    'KIWISAVER'
  ],
  property: [
    // Land Tax
    'LAND_TAX_NSW', 'LAND_TAX_VIC', 'LAND_TAX_QLD', 'LAND_TAX_SA',
    'LAND_TAX_WA', 'LAND_TAX_TAS', 'LAND_TAX_ACT',
    // Stamp Duty - Property
    'STAMP_DUTY_PROPERTY_NSW', 'STAMP_DUTY_PROPERTY_VIC',
    'STAMP_DUTY_PROPERTY_QLD', 'STAMP_DUTY_PROPERTY_SA',
    'STAMP_DUTY_PROPERTY_WA', 'STAMP_DUTY_PROPERTY_TAS',
    'STAMP_DUTY_PROPERTY_NT', 'STAMP_DUTY_PROPERTY_ACT',
    // Foreign Surcharges
    'FOREIGN_SURCHARGE_NSW', 'FOREIGN_SURCHARGE_VIC',
    'FOREIGN_SURCHARGE_QLD', 'ABSENTEE_OWNER_VIC'
  ],
  vehicle: [
    // Vehicle Registration
    'VEHICLE_REGO_NSW', 'VEHICLE_REGO_VIC', 'VEHICLE_REGO_QLD',
    'VEHICLE_REGO_SA', 'VEHICLE_REGO_WA', 'VEHICLE_REGO_TAS',
    'VEHICLE_REGO_NT', 'VEHICLE_REGO_ACT',
    // Stamp Duty - Vehicle
    'STAMP_DUTY_VEHICLE_NSW', 'STAMP_DUTY_VEHICLE_VIC',
    'STAMP_DUTY_VEHICLE_QLD', 'STAMP_DUTY_VEHICLE_SA',
    'STAMP_DUTY_VEHICLE_WA', 'STAMP_DUTY_VEHICLE_TAS',
    'STAMP_DUTY_VEHICLE_NT', 'STAMP_DUTY_VEHICLE_ACT'
  ],
  industry: [
    // Mining
    'MINING_ROYALTIES_NSW', 'MINING_ROYALTIES_VIC', 'MINING_ROYALTIES_QLD',
    'MINING_ROYALTIES_SA', 'MINING_ROYALTIES_WA', 'MINING_ROYALTIES_TAS',
    'MINING_ROYALTIES_NT',
    // Gaming
    'GAMING_TAX_NSW', 'GAMING_TAX_VIC', 'GAMING_TAX_QLD',
    'GAMING_TAX_SA', 'GAMING_TAX_WA', 'GAMING_TAX_TAS',
    'GAMING_TAX_NT', 'GAMING_TAX_ACT',
    // Environmental
    'ENVIRONMENTAL_LEVY', 'WASTE_LEVY'
  ],
  insurance: [
    // Stamp Duty - Insurance
    'STAMP_DUTY_INSURANCE_NSW', 'STAMP_DUTY_INSURANCE_VIC',
    'STAMP_DUTY_INSURANCE_QLD', 'STAMP_DUTY_INSURANCE_SA',
    'STAMP_DUTY_INSURANCE_WA', 'STAMP_DUTY_INSURANCE_TAS',
    'STAMP_DUTY_INSURANCE_NT', 'STAMP_DUTY_INSURANCE_ACT'
  ],
  emergency: [
    // Emergency Services Levies
    'EMERGENCY_SERVICES_LEVY_NSW', 'EMERGENCY_SERVICES_LEVY_VIC',
    'EMERGENCY_SERVICES_LEVY_SA', 'EMERGENCY_SERVICES_LEVY_TAS',
    'FIRE_SERVICES_LEVY_NSW', 'FIRE_SERVICES_LEVY_VIC'
  ]
};